apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"port":30564,"protocol":"TCP","serviceName":"nginx:nginx-nodeport","allNodes":true}]
    field.cattle.io/targetWorkloadIds: '["nginx/nginx"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2024-02-18T12:10:04Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"fd5d1cd0-de11-448a-90d2-344da7da4658"}: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-02-18T12:10:04Z'
  name: nginx-nodeport
  namespace: nginx
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: nginx
      uid: fd5d1cd0-de11-448a-90d2-344da7da4658
  resourceVersion: '620894'
  uid: d4e94fba-52f4-4b94-9c12-53cd44f46507
spec:
  clusterIP: 10.104.16.235
  clusterIPs:
    - 10.104.16.235
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nginx-svc
      nodePort: 30564
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-nginx-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
